name: jiudian-UDP-get  #这个是采集组播源


on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v2
    
      - name: 设置 Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: 安装依赖
        run: sudo apt-get install python3-dev     

      - name: 安装依赖
        run: pip install selenium requests futures eventlet

      - name: 安装依赖1
        run: pip install beautifulsoup4
      - name: 安装依赖2
        run: pip install playwright        
      - name: 安装依赖3
        run: pip install github3.py        
      - name: 安装依赖4
        run: pip install github  
      - name: 安装依赖5
        run: pip install --upgrade pip
      - name: 安装依赖6
        run: pip install --no-cache-dir aiohttp  


      - name: 运行UDP源采集脚本
        run: |
          nohup python ${{ github.workspace }}/py/zubo-caiji.py
      - name: 合并文件
        run: python ${{ github.workspace }}/py/hebing.py
      - name: 提交更改
        run: |
          git config --local user.email "actions@github.com"  # 设置 Git 用户邮箱
          git config --local user.name "GitHub Action"  # 设置 Git 用户名
          git add /*  # 添加 / 目录下的所有文件

          git commit -m "$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S') ：采集UDP"
          #git pull --rebase
          git push -f
